# Wraith Configuration - MVP Version

[server]
bind_address = "127.0.0.1"
port = 8080
max_connections = 1000

[static_files]
enabled = true
root = "./public"
index_files = ["index.html", "index.htm"]
compression = true

[admin]
enabled = true
bind_address = "127.0.0.1"
port = 9090