# Wraith Default Configuration
# This is a minimal working configuration for development

[server]
listen = ["0.0.0.0:9000"]
listen_tls = []
worker_threads = 0  # auto-detect

[tls]
cert_dir = "/etc/wraith/certs"
acme_enabled = false
acme_email = null

[logging]
level = "info"
format = "text"
output = "stdout"

# Example upstream (localhost:8080)
[[upstream]]
name = "localhost"
servers = [
  { host = "127.0.0.1:8080", weight = 1 },
]
load_balancing = "round_robin"
health_check = { interval = "10s", timeout = "5s", path = "/" }

# Default route
[[route]]
host = "*"
path = "/"
upstream = "localhost"
